=== KhronosGroup/OpenXR-Inventory/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "definitions": {
        "extension_name": {
            "type": "string",
            "description": "Name of an OpenXR extension",
            "pattern": "^XR_([A-Z]+)(_([a-zA-Z0-9])+)+$"
        },
        "extension_with_details": {
            "type": "object",
            "properties": {
                "name": {
                    "allOf": [
                        {
                            "title": "Extension name"
                        },
                        {
                            "$ref": "#/definitions/extension_name"
                        }
                    ]
                },
                "notes": {
                    "type": "string",
                    "title": "Notes",
                    "description": "Free-form text about support of this extension"
                }
            },
            "required": [
                "name",
                "notes"
            ]
        },
        "extension": {
            "allOf": [
                {
                    "title": "Supported Extension"
                },
                {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/extension_name"
                        },
                        {
                            "$ref": "#/definitions/extension_with_details"
                        }
                    ]
                }
            ],
            "examples": [
                "XR_KHR_composition_layer_cylinder",
                {
                    "name": "XR_EXT_hand_tracking",
                    "notes": "Currently in beta"
                }
            ]
        },
        "platform": {
            "type": "string",
            "enum": [
                "Windows (Desktop)",
                "Windows (HoloLens 2)",
                "Linux (Desktop/Embedded)",
                "Android (All-in-one)",
                "Android (Phone/Installable)"
            ]
        },
        "form_factor": {
            "type": "string",
            "title": "XrFormFactor",
            "enum": [
                "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
                "XR_FORM_FACTOR_HANDHELD_DISPLAY"
            ]
        },
        "view_configuration": {
            "type": "string",
            "title": "XrViewConfigurationType",
            "enum": [
                "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_MONO",
                "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_QUAD_VARJO",
                "XR_VIEW_CONFIGURATION_TYPE_SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT"
            ]
        },
        "environment_blend_mode": {
            "type": "string",
            "enum": [
                "OPAQUE",
                "ADDITIVE",
                "ALPHA_BLEND"
            ]
        },
        "view_configuration_data": {
            "type": "object",
            "title": "View Configuration Data",
            "properties": {
                "view_configuration": {
                    "$ref": "#/definitions/view_configuration"
                },
                "secondary_msft": {
                    "title": "Secondary (MSFT) view configuration?",
                    "type": "boolean",
                    "default": false
                },
                "environment_blend_modes": {
                    "title": "Supported environment blend modes in this view configuration",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/environment_blend_mode"
                    },
                    "minItems": 1
                }
            },
            "required": [
                "view_configuration",
                "environment_blend_modes"
            ]
        },
        "form_factor_data": {
            "type": "object",
            "title": "Form Factor Data",
            "properties": {
                "form_factor": {
                    "$ref": "#/definitions/form_factor"
                },
                "view_configurations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view_configuration_data"
                    },
                    "minItems": 1
                }
            },
            "required": [
                "form_factor",
                "view_configurations"
            ]
        }
    },
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "title": "Runtime Name"
        },
        "vendor": {
            "type": "string",
            "title": "Vendor"
        },
        "platform": {
            "$comment": "If your runtime supports more than one platform, make multiple inventory files. This keeps the schema simpler.",
            "$ref": "#/definitions/platform"
        },
        "updated": {
            "type": "string",
            "title": "Last updated",
            "description": "Date this document was last reflective of the reality"
        },
        "conformance_submission": {
            "type": "integer",
            "title": "Conformance submission number",
            "description": "See anchors at https://www.khronos.org/conformance/adopters/conformant-products/openxr"
        },
        "conformance_notes": {
            "type": "string",
            "title": "Conformance description"
        },
        "notes": {
            "type": "string",
            "title": "Notes",
            "description": "Freeform notes about this data file"
        },
        "extensions": {
            "title": "Supported extensions",
            "description": "A list of all supported extensions in this runtime, on this platform. Details or caveats may be included in 'notes'.",
            "type": "array",
            "items": {
                "$ref": "#/definitions/extension"
            }
        },
        "form_factors": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/form_factor_data"
            }
        }
    },
    "required": [
        "name",
        "vendor",
        "extensions"
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/meta_xr_simulator.json
{
    "notes": "Generated using list_json: 'Meta' (1.59.0) - simulates Quest 3",
    "$schema": "../schema.json",
    "name": "Meta XR Simulator",
    "conformance_submission": 30,
    "platform": "Windows (Desktop)",
    "vendor": "Meta Platforms",
    "extensions": [
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_convert_timespec_time", 
        "XR_KHR_D3D11_enable", 
        "XR_KHR_D3D12_enable",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_KHR_win32_convert_performance_counter_time",
        "XR_EXT_conformance_automation",
        "XR_EXT_debug_utils",
        "XR_EXT_hand_tracking",
        "XR_FB_body_tracking",
        "XR_FB_display_refresh_rate",
        "XR_FB_face_tracking",
        "XR_FB_hand_tracking_mesh",
        "XR_FB_passthrough",
        "XR_FB_render_model",
        "XR_FB_scene",
        "XR_FB_space_warp",
        "XR_FB_spatial_entity_container",
        "XR_FB_spatial_entity_query",
        "XR_FB_spatial_entity_sharing",
        "XR_FB_spatial_entity_storage_batch",
        "XR_FB_spatial_entity_storage",
        "XR_FB_spatial_entity_user",
        "XR_FB_spatial_entity",
        "XR_FB_touch_controller_pro",
        "XR_FB_triangle_mesh",
        "XR_META_headset_id",
        "XR_OCULUS_audio_device_guid"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/meta_quest_mobile.json
{
    "$schema": "../schema.json",
    "name": "Meta Quest / Quest 2 (Mobile)",
    "conformance_submission": 4,
    "platform": "Android (All-in-one)",
    "vendor": "Meta Platforms",
    "extensions": [
        "XR_KHR_android_create_instance",
        "XR_KHR_android_surface_swapchain",
        "XR_KHR_android_thread_settings",
        "XR_KHR_composition_layer_color_scale_bias",
        "XR_KHR_composition_layer_cube",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_composition_layer_equirect2",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_EXT_hand_tracking",
        "XR_EXT_performance_settings",
        "XR_FB_color_space",
        "XR_FB_composition_layer_alpha_blend",
        "XR_FB_composition_layer_image_layout",
        "XR_FB_composition_layer_secure_content",
        "XR_FB_display_refresh_rate",
        "XR_FB_foveation",
        "XR_FB_foveation_configuration",
        "XR_FB_foveation_vulkan",
        "XR_FB_hand_tracking_aim",
        "XR_FB_hand_tracking_capsules",
        "XR_FB_hand_tracking_mesh",
        "XR_FB_keyboard_tracking",
        "XR_FB_passthrough",
        "XR_FB_passthrough_keyboard_hands",
        "XR_FB_render_model",
        "XR_FB_space_warp",
        "XR_FB_swapchain_update_state",
        "XR_FB_swapchain_update_state_android_surface",
        "XR_FB_swapchain_update_state_opengl_es",
        "XR_FB_swapchain_update_state_vulkan",
        "XR_FB_triangle_mesh"
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/bytedance_pico_4_ultra.json
{
    "$schema": "../schema.json",
    "name": "Bytedance PICO 4 Ultra",
    "conformance_submission": 39,
    "platform": "Android (All-in-one)",
    "vendor": "BYTEDANCE",
    "extensions": [
        "XR_KHR_android_create_instance",
        "XR_KHR_android_surface_swapchain",
        "XR_KHR_android_thread_settings",
        "XR_KHR_composition_layer_color_scale_bias",
        "XR_KHR_composition_layer_cube",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_composition_layer_equirect",
        "XR_KHR_composition_layer_equirect2",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_loader_init",
        "XR_KHR_loader_init_android",
        "XR_KHR_maintenance1",
        "XR_KHR_opengl_enable",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_KHR_vulkan_swapchain_format_list",
        "XR_MND_headless",
        "XR_EPIC_view_configuration_fov",
        "XR_EXT_active_action_set_priority",
        "XR_EXT_composition_layer_inverted_alpha",
        "XR_EXT_debug_utils",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_future",
        "XR_EXT_hand_interaction",
        "XR_EXT_hand_tracking",
        "XR_EXT_local_floor",
        "XR_EXT_view_configuration_depth_range",
        "XR_EXT_palm_pose",
        "XR_EXT_performance_settings",
        "XR_EXT_user_presence",
        "XR_EXT_uuid",
        "XR_EXTX_overlay",
        "XR_BD_controller_interaction",
        "XR_FB_composition_layer_alpha_blend",
        "XR_FB_composition_layer_image_layout",
        "XR_FB_composition_layer_secure_content",
        "XR_FB_composition_layer_settings",
        "XR_FB_display_refresh_rate",
        "XR_FB_foveation",
        "XR_FB_foveation_configuration",
        "XR_FB_foveation_vulkan",
        "XR_FB_passthrough",
        "XR_FB_swapchain_update_state",
        "XR_FB_triangle_mesh",
        "XR_FB_space_warp",
        "XR_FB_swapchain_update_state_android_surface",
        "XR_FB_swapchain_update_state_opengl_es",
        "XR_FB_swapchain_update_state_vulkan",
        "XR_META_foveation_eye_tracked",
        "XR_META_vulkan_swapchain_create_info",
        "XR_MNDX_egl_enable",
        "XR_MSFT_composition_layer_reprojection"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE",
                        "ALPHA_BLEND"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/monado_android.json
{
    "notes": "Generated using list_json: 'Monado(XRT) by Collabora et al 'v24.0.0-367-g3009f3750'' (24.0.0)",
    "$schema": "../schema.json",
    "name": "Monado (Android)",
    "vendor": "Monado Community + Collabora, Ltd.",
    "platform": "Android (Phone/Installable)",
    "conformance_notes": "Only the 'Simulated Device' in Monado on Linux is officially conformant. Vendors building on Monado must follow the normal conformance process for their own devices.",
    "notes": "Could be built-in to an all-in-one, but Collabora does not manufacture or have system-level access to such devices. Availability of some extensions is determined by availability of dependencies at compile time. Support for some extensions and blend modes depends on the hardware in use.",
    "extensions": [
        "XR_KHR_android_create_instance",
        "XR_KHR_android_thread_settings",
        "XR_KHR_binding_modification",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_composition_layer_equirect2",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_loader_init",
        "XR_KHR_loader_init_android",
        "XR_KHR_locate_spaces",
        "XR_KHR_maintenance1",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_swapchain_usage_input_attachment_bit",
        "XR_KHR_visibility_mask",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_KHR_vulkan_swapchain_format_list",
        "XR_EXT_active_action_set_priority",
        "XR_EXT_dpad_binding",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_hand_interaction",
        "XR_EXT_hand_tracking",
        "XR_EXT_hp_mixed_reality_controller",
        "XR_EXT_local_floor",
        "XR_EXT_samsung_odyssey_controller",
        "XR_EXTX_overlay",
        "XR_BD_controller_interaction",
        "XR_FB_display_refresh_rate",
        "XR_FB_touch_controller_pro",
        "XR_FB_touch_controller_proximity",
        "XR_HTC_vive_cosmos_controller_interaction",
        "XR_HTC_vive_focus3_controller_interaction",
        "XR_META_touch_controller_plus",
        "XR_ML_ml2_controller_interaction",
        "XR_MND_headless",
        "XR_MND_swapchain_usage_input_attachment_bit",
        "XR_MNDX_force_feedback_curl",
        "XR_MSFT_unbounded_reference_space",
        "XR_OPPO_controller_interaction"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE",
                        "ADDITIVE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/htc_vive_cosmos.json
{
    "$schema": "../schema.json",
    "name": "HTC Vive Cosmos",
    "conformance_submission": 13,
    "platform": "Windows (Desktop)",
    "vendor": "HTC America, Inc.",
    "extensions": [
        "XR_KHR_composition_layer_depth",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_D3D11_enable",
        "XR_KHR_D3D12_enable",
        "XR_KHR_opengl_enable",
        "XR_KHR_visibility_mask",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_KHR_win32_convert_performance_counter_time",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_hand_joints_motion_range",
        "XR_EXT_hand_tracking",
        "XR_EXT_win32_appcontainer_compatible",
        "XR_FB_passthrough",
        "XR_FB_triangle_mesh",
        "XR_HTC_facial_tracking",
        "XR_HTC_vive_cosmos_controller_interaction",
        "XR_MSFT_scene_understanding"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE",
                        "ALPHA_BLEND"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/bytedance_pico.json
{
    "$schema": "../schema.json",
    "name": "Bytedance PICO 4 / PICO 4 Ultra / PICO Neo3",
    "conformance_submission": 25,
    "platform": "Android (All-in-one)",
    "vendor": "BYTEDANCE",
    "extensions": [
        "XR_KHR_android_create_instance",
        "XR_KHR_android_surface_swapchain",
        "XR_KHR_composition_layer_color_scale_bias",
        "XR_KHR_composition_layer_cube",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_equirect",
        "XR_KHR_composition_layer_equirect2",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_loader_init",
        "XR_KHR_loader_init_android",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_KHR_vulkan_swapchain_format_list",
        "XR_MND_headless",
        "XR_EPIC_view_configuration_fov",
        "XR_EXT_debug_utils",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_hand_tracking",
        "XR_EXT_view_configuration_depth_range",
        "XR_EXT_performance_settings",
        "XR_EXTX_overlay",
        "XR_FB_composition_layer_alpha_blend",
        "XR_FB_composition_layer_image_layout",
        "XR_FB_composition_layer_secure_content",
        "XR_FB_composition_layer_settings",
        "XR_FB_display_refresh_rate",
        "XR_FB_foveation",
        "XR_FB_foveation_configuration",
        "XR_FB_foveation_vulkan",
        "XR_FB_passthrough",
        "XR_FB_swapchain_update_state",
        "XR_FB_triangle_mesh",
        "XR_FB_space_warp",
        "XR_FB_swapchain_update_state_android_surface",
        "XR_FB_swapchain_update_state_opengl_es",
        "XR_FB_swapchain_update_state_vulkan",
        "XR_META_foveation_eye_tracked",
        "XR_META_vulkan_swapchain_create_info"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/qualcomm.json
{
    "$schema": "../schema.json",
    "name": "Monado 21.0.0 / Qualcomm Retina 1.0.0 (Snapdragon 840/865/888)",
    "conformance_submission": 16,
    "vendor": "QUALCOMM",
    "extensions": [
        "XR_KHR_android_create_instance",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_equirect",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_loader_init",
        "XR_KHR_loader_init_android",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_swapchain_usage_input_attachment_bit",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_EXT_debug_utils",
        "XR_EXT_hand_tracking",
        "XR_MND_headless",
        "XR_EXTX_overlay"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE"
                    ]
                }
            ]
        }        
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/monado_linux.json
{
    "$schema": "../schema.json",
    "name": "Monado (Desktop / Embedded Linux)",
    "vendor": "Monado Community + Collabora, Ltd.",
    "platform": "Linux (Desktop/Embedded)",
    "conformance_submission": 12,
    "conformance_notes": "Only the 'Simulated Device' in Monado on Linux is officially conformant. Vendors building on Monado must follow the normal conformance process for their own devices.",
    "notes": "Availability of some extensions is determined by availability of dependencies at compile time.",
    "extensions": [
        "XR_KHR_composition_layer_cube",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_composition_layer_equirect",
        "XR_KHR_composition_layer_equirect2",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_opengl_enable",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_swapchain_usage_input_attachment_bit",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_EXT_hand_tracking",
        {
            "name": "XR_FB_display_refresh_rate",
            "notes": "Not useful on all drivers"
        },
        "XR_MND_headless",
        "XR_MND_swapchain_usage_input_attachment_bit",
        "XR_EXTX_overlay",
        "XR_MNDX_egl_enable"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE",
                        "ADDITIVE"
                    ]
                }
            ]
        }
    ]
}
