=== KhronosGroup/OpenXR-Inventory/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "definitions": {
        "extension_name": {
            "type": "string",
            "description": "Name of an OpenXR extension",
            "pattern": "^XR_([A-Z]+)(_([a-zA-Z0-9])+)+$"
        },
        "extension_with_details": {
            "type": "object",
            "properties": {
                "name": {
                    "allOf": [
                        {
                            "title": "Extension name"
                        },
                        {
                            "$ref": "#/definitions/extension_name"
                        }
                    ]
                },
                "notes": {
                    "type": "string",
                    "title": "Notes",
                    "description": "Free-form text about support of this extension"
                }
            },
            "required": [
                "name",
                "notes"
            ]
        },
        "extension": {
            "allOf": [
                {
                    "title": "Supported Extension"
                },
                {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/extension_name"
                        },
                        {
                            "$ref": "#/definitions/extension_with_details"
                        }
                    ]
                }
            ],
            "examples": [
                "XR_KHR_composition_layer_cylinder",
                {
                    "name": "XR_EXT_hand_tracking",
                    "notes": "Currently in beta"
                }
            ]
        },
        "platform": {
            "type": "string",
            "enum": [
                "Windows (Desktop)",
                "Windows (HoloLens 2)",
                "Linux (Desktop/Embedded)",
                "Android (All-in-one)",
                "Android (Phone/Installable)"
            ]
        },
        "form_factor": {
            "type": "string",
            "title": "XrFormFactor",
            "enum": [
                "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
                "XR_FORM_FACTOR_HANDHELD_DISPLAY"
            ]
        },
        "view_configuration": {
            "type": "string",
            "title": "XrViewConfigurationType",
            "enum": [
                "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_MONO",
                "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_QUAD_VARJO",
                "XR_VIEW_CONFIGURATION_TYPE_SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT"
            ]
        },
        "environment_blend_mode": {
            "type": "string",
            "enum": [
                "OPAQUE",
                "ADDITIVE",
                "ALPHA_BLEND"
            ]
        },
        "view_configuration_data": {
            "type": "object",
            "title": "View Configuration Data",
            "properties": {
                "view_configuration": {
                    "$ref": "#/definitions/view_configuration"
                },
                "secondary_msft": {
                    "title": "Secondary (MSFT) view configuration?",
                    "type": "boolean",
                    "default": false
                },
                "environment_blend_modes": {
                    "title": "Supported environment blend modes in this view configuration",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/environment_blend_mode"
                    },
                    "minItems": 1
                }
            },
            "required": [
                "view_configuration",
                "environment_blend_modes"
            ]
        },
        "form_factor_data": {
            "type": "object",
            "title": "Form Factor Data",
            "properties": {
                "form_factor": {
                    "$ref": "#/definitions/form_factor"
                },
                "view_configurations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view_configuration_data"
                    },
                    "minItems": 1
                }
            },
            "required": [
                "form_factor",
                "view_configurations"
            ]
        }
    },
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "title": "Runtime Name"
        },
        "vendor": {
            "type": "string",
            "title": "Vendor"
        },
        "platform": {
            "$comment": "If your runtime supports more than one platform, make multiple inventory files. This keeps the schema simpler.",
            "$ref": "#/definitions/platform"
        },
        "updated": {
            "type": "string",
            "title": "Last updated",
            "description": "Date this document was last reflective of the reality"
        },
        "conformance_submission": {
            "type": "integer",
            "title": "Conformance submission number",
            "description": "See anchors at https://www.khronos.org/conformance/adopters/conformant-products/openxr"
        },
        "conformance_notes": {
            "type": "string",
            "title": "Conformance description"
        },
        "notes": {
            "type": "string",
            "title": "Notes",
            "description": "Freeform notes about this data file"
        },
        "extensions": {
            "title": "Supported extensions",
            "description": "A list of all supported extensions in this runtime, on this platform. Details or caveats may be included in 'notes'.",
            "type": "array",
            "items": {
                "$ref": "#/definitions/extension"
            }
        },
        "form_factors": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/form_factor_data"
            }
        }
    },
    "required": [
        "name",
        "vendor",
        "extensions"
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/monado_windows.json
{
    "$schema": "../schema.json",
    "name": "Monado (Windows)",
    "vendor": "Monado Community + Collabora, Ltd.",
    "platform": "Windows (Desktop)",
    "conformance_notes": "Only the 'Simulated Device' in Monado on Linux is officially conformant. Vendors building on Monado must follow the normal conformance process for their own devices.",
    "notes": "Availability of some extensions is determined by availability of dependencies at compile time.",
    "extensions": [
        "XR_KHR_composition_layer_cube",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_composition_layer_equirect",
        "XR_KHR_composition_layer_equirect2",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_win32_convert_performance_counter_time",
        "XR_KHR_D3D11_enable",
        "XR_KHR_swapchain_usage_input_attachment_bit",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_EXT_hand_tracking",
        {
            "name": "XR_FB_display_refresh_rate",
            "notes": "Not useful on all drivers"
        },
        "XR_MND_headless",
        "XR_MND_swapchain_usage_input_attachment_bit"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE",
                        "ADDITIVE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/magicleap_remote_rendering.json
{
    "$schema": "../schema.json",
    "name": "Magic Leap Remote Rendering",
    "conformance_submission": 27,
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "ADDITIVE",
                        "ALPHA_BLEND"
                    ]
                }
            ]
        }
    ],
    "platform": "Windows (Desktop)",
    "vendor": "Magic Leap",
    "updated": "November 13, 2023",
    "extensions": [
		"XR_EXT_dpad_binding",
		"XR_EXT_eye_gaze_interaction",
		"XR_EXT_hand_interaction",
		"XR_EXT_hand_tracking",
		"XR_EXT_plane_detection",
		"XR_KHR_D3D11_enable",
		"XR_KHR_D3D12_enable",
		"XR_KHR_composition_layer_cylinder",
		"XR_KHR_composition_layer_depth",
		"XR_KHR_composition_layer_equirect2",
		"XR_KHR_opengl_enable",
		"XR_KHR_vulkan_enable",
		"XR_KHR_vulkan_enable2",
		"XR_KHR_win32_convert_performance_counter_time",
		"XR_ML_global_dimmer",
		"XR_ML_ml2_controller_interaction",
		"XR_KHR_binding_modification",
		"XR_MND_swapchain_usage_input_attachment_bit",
		"XR_KHR_swapchain_usage_input_attachment_bit",
		"XR_EXT_debug_utils"
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/magicleap_ml2.json
{
    "$schema": "../schema.json",
    "name": "Magic Leap ML2",
    "conformance_submission": 26,
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "ADDITIVE",
                        "ALPHA_BLEND"
                    ]
                }
            ]
        }
    ],
    "platform": "Android (All-in-one)",
    "vendor": "Magic Leap",
    "extensions": [
        "XR_KHR_android_create_instance",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_opengl_enable",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_vulkan_enable",
        "XR_EXT_conformance_automation",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_hand_tracking",
        "XR_EXT_view_configuration_depth_range",
        "XR_ML_compat",
        "XR_ML_frame_end_info",
        "XR_ML_global_dimmer",
        "XR_ML_ml2_controller_interaction",
        "XR_MND_headless"
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/valve_steamvr.json
{
    "notes": "Generated using list_json: 'SteamVR/OpenXR' (0.1.0)",
    "$schema": "../schema.json",
    "name": "SteamVR",
    "conformance_submission": 11,
    "platform": "Windows (Desktop)",
    "vendor": "Valve Corporation",
    "extensions": [
        "XR_KHR_binding_modification",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_D3D11_enable",
        "XR_KHR_D3D12_enable",
        "XR_KHR_opengl_enable",
        "XR_KHR_visibility_mask",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_KHR_win32_convert_performance_counter_time",
        "XR_EXT_dpad_binding",
        "XR_EXT_hand_joints_motion_range",
        "XR_EXT_hand_tracking",
        "XR_EXT_hp_mixed_reality_controller",
        "XR_EXT_palm_pose",
        "XR_EXT_win32_appcontainer_compatible",
        "XR_FB_display_refresh_rate",
        "XR_HTC_vive_cosmos_controller_interaction",
        "XR_HTC_vive_focus3_controller_interaction",
        "XR_HTCX_vive_tracker_interaction",
        "XR_MND_headless",
        "XR_VALVE_analog_threshold"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/mbucchia_pimaxxr.json
{
    "$schema": "../schema.json",
    "name": "PimaxXR",
    "vendor": "Matthieu Bucchianeri",
    "platform": "Windows (Desktop)",
    "notes": "Generated using list_json: 'PimaxXR (Unofficial)' (0.4.4)",
    "extensions": [
        "XR_KHR_composition_layer_depth",
        "XR_KHR_D3D11_enable",
        "XR_KHR_D3D12_enable",
        "XR_KHR_opengl_enable",
        "XR_KHR_visibility_mask",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_KHR_win32_convert_performance_counter_time",
        {
            "name": "XR_EXT_eye_gaze_interaction",
            "notes": "Functional with Pimax Crystal or Pimax Droolon Pi1 modules"
        },
        "XR_EXT_hand_joints_motion_range",
        "XR_EXT_hand_tracking",
        "XR_FB_display_refresh_rate"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/htc_vive_focus.json
{
    "notes": "Generated using list_json: 'VIVE WAVE' (0.0.1)",
    "$schema": "../schema.json",
    "name": "HTC Vive Focus 3",
    "conformance_submission": 21,
    "platform": "Android (All-in-one)",
    "vendor": "HTC America, Inc.",
    "extensions": [
        "XR_KHR_android_create_instance",
        "XR_KHR_android_surface_swapchain",
        "XR_KHR_composition_layer_color_scale_bias",
        "XR_KHR_composition_layer_cylinder",
        "XR_KHR_composition_layer_equirect",
        "XR_KHR_composition_layer_equirect2",
        "XR_KHR_convert_timespec_time",
        "XR_KHR_loader_init",
        "XR_KHR_loader_init_android",
        "XR_KHR_opengl_es_enable",
        "XR_KHR_visibility_mask",
        "XR_KHR_vulkan_enable",
        "XR_KHR_vulkan_enable2",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_future",
        "XR_EXT_hand_interaction",
        "XR_EXT_hand_tracking",
        "XR_EXT_palm_pose",
        "XR_EXT_performance_settings",
        "XR_EXT_plane_detection",
        "XR_EXT_user_presence",
        "XR_FB_display_refresh_rate",
        "XR_FB_keyboard_tracking",
        "XR_HTC_anchor",
        "XR_HTC_facial_tracking",
        "XR_HTC_foveation",
        "XR_HTC_hand_interaction",
        "XR_HTC_passthrough",
        "XR_HTC_vive_focus3_controller_interaction",
        "XR_HTC_vive_wrist_tracker_interaction",
        "XR_MSFT_first_person_observer",
        "XR_MSFT_secondary_view_configuration"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "OPAQUE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/microsoft_hololens2.json
{
    "$schema": "../schema.json",
    "name": "Windows Mixed Reality - HoloLens 2",
    "conformance_submission": 1,
    "platform": "Windows (HoloLens 2)",
    "vendor": "Microsoft Corporation",
    "extensions": [
        "XR_KHR_composition_layer_color_scale_bias",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_D3D11_enable",
        "XR_KHR_D3D12_enable",
        "XR_KHR_win32_convert_performance_counter_time",
        "XR_EXT_conformance_automation",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_hand_joints_motion_range",
        "XR_EXT_hand_tracking",
        "XR_EXT_palm_pose",
        "XR_EXT_win32_appcontainer_compatible",
        "XR_FB_display_refresh_rate",
        "XR_MSFT_composition_layer_reprojection",
        "XR_MSFT_first_person_observer",
        "XR_MSFT_hand_interaction",
        "XR_MSFT_hand_tracking_mesh",
        "XR_MSFT_holographic_window_attachment",
        "XR_MSFT_perception_anchor_interop",
        "XR_MSFT_scene_understanding",
        "XR_MSFT_scene_understanding_serialization",
        "XR_MSFT_secondary_view_configuration",
        "XR_MSFT_spatial_anchor",
        "XR_MSFT_spatial_anchor_persistence",
        "XR_MSFT_spatial_graph_bridge",
        "XR_MSFT_unbounded_reference_space"
    ],
    "form_factors": [
        {
            "form_factor": "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY",
            "view_configurations": [
                {
                    "view_configuration": "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO",
                    "environment_blend_modes": [
                        "ADDITIVE"
                    ]
                }
            ]
        }
    ]
}

=== KhronosGroup/OpenXR-Inventory/runtimes/microsoft_pc.json
{
    "$schema": "../schema.json",
    "name": "Windows Mixed Reality",
    "conformance_submission": 1,
    "platform": "Windows (Desktop)",
    "notes": "Also for HoloLens 2 all-in-one",
    "vendor": "Microsoft Corporation",
    "extensions": [
        "XR_KHR_composition_layer_color_scale_bias",
        "XR_KHR_composition_layer_depth",
        "XR_KHR_D3D11_enable",
        "XR_KHR_D3D12_enable",
        "XR_KHR_visibility_mask",
        "XR_KHR_win32_convert_performance_counter_time",
        "XR_EXT_conformance_automation",
        "XR_EXT_eye_gaze_interaction",
        "XR_EXT_hand_joints_motion_range",
        "XR_EXT_hand_tracking",
        "XR_EXT_hp_mixed_reality_controller",
        "XR_EXT_samsung_odyssey_controller",
        "XR_EXT_win32_appcontainer_compatible",
        "XR_MSFT_composition_layer_reprojection",
        "XR_MSFT_controller_model",
        "XR_MSFT_first_person_observer",
        "XR_MSFT_hand_interaction",
        "XR_MSFT_hand_tracking_mesh",
        "XR_MSFT_holographic_window_attachment",
        "XR_MSFT_perception_anchor_interop",
        "XR_MSFT_scene_understanding",
        "XR_MSFT_scene_understanding_serialization",
        "XR_MSFT_secondary_view_configuration",
        "XR_MSFT_spatial_anchor",
        "XR_MSFT_spatial_anchor_persistence",
        "XR_MSFT_spatial_graph_bridge",
        "XR_MSFT_unbounded_reference_space"
    ]
}
